[package]
name = "sharp-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "sharp"
path = "src/main.rs"

[dependencies]
sharp-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
